### PR TITLE
33 implement score. Closes #33

### LINKED ISSUE #33: Implement Score
- [x] Show the score as a HUD
- [ ] Save highscores

### PR DESCRIPTION
**Pull request by eliassoon**

### CODE REVIEW

**Comment by sutbult** [comment]
I don't think that you have understood the purpose of the Application interface. The interface is pretty much done and you are supposed to integrate whatever graphics you build with the existing functions and not change it every time, so that it becomes as generic as possible.

Fix the score so that it uses the existing renderText method and remove everything that has to do with "renderHud". Please consult me in the future if you want to change the Application interface in any way.

**Comment by sutbult** [comment]
- [ ] Remove the "isHud" parameter to renderText
- [ ] Remove ALL changes to SwingApplication. You should not have to change it at all.
- [ ] Create a separate camera that is used for the HUD. Look in the init method for clues on how to change the current camera.

**Comment by sutbult** [comment]
Have you read my messages?

**Comment by eliassoon** [comment]
Yes? IsHud is removed and renderText is restored.  Although your description is contradicting on how to handle the camera for the HUD, I made a choice to make a separate camera and use it in renderText to manipulate the position for the text.

**Comment by sutbult** [comment]
Let's talk about it on wednesday instead.

**Pull request merged**
